# Automate, customize, and execute your software development workflows right in your repository with GitHub Actions.
# Documentation: https://docs.github.com/en/actions

name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        id: install-dependencies
        run: yarn install

      - name: Lint code
        id: lint
        run: npm run lint

  test:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        id: install-dependencies
        run: yarn install

      - name: Test code
        id: lint
        run: npm run test



  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    needs: lint

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        id: install-dependencies
        run: npm install

      - name: Try to build the packages
        id: build-packages
        run: npm run build:ci

